from fastapi import status

HTTP_OK = status.HTTP_200_OK

HTTP_CREATED = status.HTTP_201_CREATED

HTTP_BAD_REQUEST = status.HTTP_400_BAD_REQUEST

HTTP_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED

HTTP_FORBIDDEN = status.HTTP_403_FORBIDDEN

HTTP_NOT_FOUND = status.HTTP_404_NOT_FOUND

HTTP_CONFLICT = status.HTTP_409_CONFLICT

HTTP_INTERNAL_SERVER_ERROR = (
    status.HTTP_500_INTERNAL_SERVER_ERROR
)