package com.example.springcoreassignment.component;

import org.springframework.stereotype.Component;

// Implementation of MessageFormatter for long messages
@Component
public class LongMessageFormatter implements MessageFormatter {

    @Override
    public String formatMessage() {
        return "This is a long formatted message generated by the system.";
    }

    @Override
    public String getType() {
        return "LONG";
    }
}