from enum import Enum


class Specialization(str, Enum):
    """Doctor specializations supported for registration and search."""

    GENERAL_PHYSICIAN = "GENERAL_PHYSICIAN"
    CARDIOLOGIST = "CARDIOLOGIST"
    DERMATOLOGIST = "DERMATOLOGIST"
    DENTIST = "DENTIST"
    NEUROLOGIST = "NEUROLOGIST"
    ORTHOPEDIC = "ORTHOPEDIC"
    PEDIATRICIAN = "PEDIATRICIAN"
    GYNECOLOGIST = "GYNECOLOGIST"
    ENT_SPECIALIST = "ENT_SPECIALIST"
    PSYCHIATRIST = "PSYCHIATRIST"
    OPHTHALMOLOGIST = "OPHTHALMOLOGIST"
    UROLOGIST = "UROLOGIST"
    GASTROENTEROLOGIST = "GASTROENTEROLOGIST"
    PULMONOLOGIST = "PULMONOLOGIST"
    ENDOCRINOLOGIST = "ENDOCRINOLOGIST"
